import { IBank, IBankAccount } from '@/interfaces';

export const dummyBanks: IBank[] = [
  {
    name: 'Zenith Bank',
    code: '057',
    country: 'Nigeria',
    currency: 'NGN',
    id: 1,
    longcode: '057150013',
    slug: 'zenith-bank',
  },
  {
    name: 'GTBank',
    code: '058',
    country: 'Nigeria',
    currency: 'NGN',
    id: 2,
    longcode: '058152036',
    slug: 'gtbank',
  },
  {
    name: 'Access Bank',
    code: '044',
    country: 'Nigeria',
    currency: 'NGN',
    id: 3,
    longcode: '044150149',
    slug: 'access-bank',
  },
  {
    name: 'First Bank of Nigeria',
    code: '011',
    country: 'Nigeria',
    currency: 'NGN',
    id: 4,
    longcode: '011151003',
    slug: 'first-bank-of-nigeria',
  },
  {
    name: 'UBA',
    code: '033',
    country: 'Nigeria',
    currency: 'NGN',
    id: 5,
    longcode: '033153513',
    slug: 'uba',
  },
  {
    name: 'Fidelity Bank',
    code: '070',
    country: 'Nigeria',
    currency: 'NGN',
    id: 6,
    longcode: '070150003',
    slug: 'fidelity-bank',
  },
  {
    name: 'Union Bank',
    code: '032',
    country: 'Nigeria',
    currency: 'NGN',
    id: 7,
    longcode: '032080474',
    slug: 'union-bank',
  },
  {
    name: 'Sterling Bank',
    code: '232',
    country: 'Nigeria',
    currency: 'NGN',
    id: 8,
    longcode: '232150016',
    slug: 'sterling-bank',
  },
  {
    name: 'Ecobank Nigeria',
    code: '050',
    country: 'Nigeria',
    currency: 'NGN',
    id: 9,
    longcode: '050150005',
    slug: 'ecobank-nigeria',
  },
  {
    name: 'Polaris Bank',
    code: '076',
    country: 'Nigeria',
    currency: 'NGN',
    id: 10,
    longcode: '076151006',
    slug: 'polaris-bank',
  },
  {
    name: 'Wema Bank',
    code: '035',
    country: 'Nigeria',
    currency: 'NGN',
    id: 11,
    longcode: '035150103',
    slug: 'wema-bank',
  },
  {
    name: 'Keystone Bank',
    code: '082',
    country: 'Nigeria',
    currency: 'NGN',
    id: 12,
    longcode: '082150017',
    slug: 'keystone-bank',
  },
];

export const dummyAccounts: IBankAccount[] = [
  {
    id: '1',
    account_name: 'John Doe',
    account_number: '1234567890',
    bank_code: '057',
    bank_name: 'Zenith Bank',
    is_default: true,
    recipient_code: 'zenith123',
  },
  {
    id: '2',
    account_name: 'Jane Smith',
    account_number: '2345678901',
    bank_code: '058',
    bank_name: 'GTBank',
    is_default: false,
    recipient_code: 'gtb234',
  },
  {
    id: '3',
    account_name: 'Michael Johnson',
    account_number: '3456789012',
    bank_code: '044',
    bank_name: 'Access Bank',
    is_default: false,
    recipient_code: 'access345',
  },
  // {
  //   id: '4',
  //   account_name: 'Ngozi Okafor',
  //   account_number: '4567890123',
  //   bank_code: '011',
  //   bank_name: 'First Bank of Nigeria',
  //   is_default: false,
  //   recipient_code: 'first456',
  // },
  // {
  //   id: '5',
  //   account_name: 'David Ade',
  //   account_number: '5678901234',
  //   bank_code: '033',
  //   bank_name: 'UBA',
  //   is_default: false,
  //   recipient_code: 'uba567',
  // },
  // {
  //   id: '6',
  //   account_name: 'Amina Bala',
  //   account_number: '6789012345',
  //   bank_code: '070',
  //   bank_name: 'Fidelity Bank',
  //   is_default: false,
  //   recipient_code: 'fidelity678',
  // },
  // {
  //   id: '7',
  //   account_name: 'Tolu Eze',
  //   account_number: '7890123456',
  //   bank_code: '032',
  //   bank_name: 'Union Bank',
  //   is_default: false,
  //   recipient_code: 'union789',
  // },
  // {
  //   id: '8',
  //   account_name: 'Chika Obi',
  //   account_number: '8901234567',
  //   bank_code: '232',
  //   bank_name: 'Sterling Bank',
  //   is_default: false,
  //   recipient_code: 'sterling890',
  // },
  // {
  //   id: '9',
  //   account_name: 'Emeka Nwosu',
  //   account_number: '9012345678',
  //   bank_code: '050',
  //   bank_name: 'Ecobank Nigeria',
  //   is_default: false,
  //   recipient_code: 'eco901',
  // },
  // {
  //   id: '10',
  //   account_name: 'Bola Hassan',
  //   account_number: '0123456789',
  //   bank_code: '076',
  //   bank_name: 'Polaris Bank',
  //   is_default: false,
  //   recipient_code: 'polaris012',
  // },
];
